
services:
  webchat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_APPLICATION_NAME=WebChatApp
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/websocket


  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"